# Generated by Django 4.0.1 on 2022-01-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(max_length=800)),
                ('recipeurl', models.URLField(blank=True)),
                ('recipeimage', models.ImageField(upload_to='profile_pics')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
